config/routes.rb
MakeSandwich::Application.routes.draw do
  root :to => 'orders#new'

  devise_for :users
  resources :orders
  

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :sandwich, :user
  belongs_to :user
  after_create :email_after_order
  
  def email_after_order
    RestClient.post("https://api:key-26mzn1uxlj1zk7c5xnszcbbxgkhy1ne8"\
                     "@api.mailgun.net/v2/aboxofpaints.mailgun.org/messages",
                      :from => 'David McDonald <david@aboxofpaints.com>',
                      :to => 'make_sandwich@generalthings.com',
                      :subject => "A #{self.sandwich} has been ordered.",
                      :text => "A call to arms is at hand!\n
          #{self.user.email} ordered a #{self.sandwich}.\n
          WERQ.\n
          \"There's nothing like unrequited love to take all the flavor out of a peanut butter sandwich.\" - Charlie Brown \n
                                ")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!, :except => [:new]
  def new
    @order = Order.new
  end

  def create
    @order = current_user.orders.build(params[:order])
    @order.save
      redirect_to @order, :notice => "Deliciousness awaits."
  end

  def show
    @order = Order.find(params[:id])
  end

  def index
    @orders = Order.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Make Sandwich" %></title>
    <%= csrf_meta_tags %>

    

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Time to eat!</a>
          <div class="container nav-collapse">
            <ul class="nav">
							<% if signed_in? %>
              <li><%= link_to "Signed in as #{current_user.email}", edit_user_registration_path %></li>
							<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
              <% else %>
				        <li><%= link_to "Sign Up", new_user_registration_path %>
				        <li><%= link_to "Sign In", new_user_session_path %></li>
				      <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span12">

	           <% if notice %>
               <p class="alert alert-success"><%= notice %></p>
             <% end %>
             <% if alert %>
               <p class="alert alert-error"><%= alert %></p>
             <% end %>

              <%= yield %>
            </div>
        </div>
      </div>

      <footer>
        <p>	 </p>
      </footer>

    </div>

    
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>
<h1>  Pick a Sandwich: <h1>
  <div class="field">
    <%= f.select :sandwich, [['BLT','BLT'],['Rueben','Rueben'],['Po Boy','Po Boy']] %>
   </div>


  


  <div class="actions">
    <%= f.submit "ORDER", :class => 'btn btn-primary btn-large' %>
  </div>

<% end %>

app/views/orders/create.html.erb
<h1>Order#create</h1>
<p>Find me in app/views/order/create.html.erb</p>

app/views/orders/index.html.erb
<h1>Past Orders </h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>

<tr>
  
		<td> <%= order.sandwich %> was ordered at <%= order.created_at.strftime("%Y-%m-%d %H:%M") %> by <%= order.user.email%> </td>
</tr>


<% end %>
</table>

<br />


<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>Create a New Order!</h1>
<!-- <p>Find me in app/views/order/new.html.erb</p> -->
<%= render 'form' %>
<br />
<br />
<br />

<h5><%= link_to 'History', orders_path %></h5>

app/views/orders/show.html.erb
<h1>Your Order</h1>
<p>You got a <%=@order.sandwich%>. Grab a napkin.</p>

<%= link_to 'History', orders_path %>